const $=s=>document.querySelector(s);const screens=['home','create','result','battle'];let monster=null;
const emojis=['🦝','🦈','🐸','🦆','🦑','🐲','🦄','🍌','🧃','🦖','🐙','🥔'];const traits=['SUPREMO','NINJA','DESTROYER','GOBLIN','WARRIOR','BOSS','PROPHET','MENACE'];const lore=['escaped from a suspicious supermarket at 3AM.','was banned from three dimensions for excessive aura.','has one mission: become ridiculously famous.','looks harmless. It is absolutely not.','was created by accident and refuses to apologize.'];
function show(id){screens.forEach(x=>$('#'+x).classList.toggle('active',x===id));scrollTo(0,0)}
function hash(s){let h=0;for(let i=0;i<s.length;i++)h=((h<<5)-h)+s.charCodeAt(i)|0;return Math.abs(h)}
function generate(){const raw=$('#nameInput').value.trim()||'Anonymous';const h=hash(raw+Date.now());const e=emojis[h%emojis.length];const suffix=traits[Math.floor(h/7)%traits.length];const stats=[58+(h%43),55+((h>>3)%46),50+((h>>6)%50),60+((h>>9)%40)];const power=Math.round(stats.reduce((a,b)=>a+b,0)/4);const rarity=power>90?'MYTHIC':power>78?'LEGENDARY':power>65?'EPIC':'UNCOMMON';monster={name:(raw+' '+suffix).toUpperCase(),emoji:e,lore:lore[h%lore.length],stats,rarity,power};$('#monsterEmoji').textContent=e;$('#monsterName').textContent=monster.name;$('#monsterLore').textContent=monster.lore;$('#rarity').textContent=rarity;['power','chaos','luck','aura'].forEach((x,i)=>$('#'+x).textContent=stats[i]);show('result')}
$('#createBtn').onclick=()=>show('create');$('#generateBtn').onclick=generate;document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>show('home'));
$('#challengeBtn').onclick=()=>{if(!monster)return;$('#battleEmoji').textContent=monster.emoji;$('#battleName').textContent=monster.name;$('#battlePower').textContent='POWER '+monster.power;const token=btoa(unescape(encodeURIComponent(JSON.stringify(monster)))).replace(/=/g,'');const url=location.href.split('#')[0]+'#challenge='+token;$('#shareUrl').textContent=url;show('battle')};
$('#shareBtn').onclick=async()=>{if(!monster)return;const text=`I created ${monster.name} ${monster.emoji} — POWER ${monster.power}. Can you beat it?`;if(navigator.share){try{await navigator.share({title:'WHO ARE YOU?',text,url:location.href})}catch{}}else{await navigator.clipboard?.writeText(text+' '+location.href);$('#shareBtn').textContent='COPIED ✓'}};
$('#copyBtn').onclick=async()=>{await navigator.clipboard?.writeText($('#shareUrl').textContent);$('#copyBtn').textContent='COPIED ✓';setTimeout(()=>$('#copyBtn').textContent='COPY CHALLENGE LINK 🔗',1600)};
const params=location.hash;if(params.startsWith('#challenge=')){try{monster=JSON.parse(decodeURIComponent(escape(atob(params.slice(11)))));setTimeout(()=>{generateFromShared(monster)},100)}catch{}}
function generateFromShared(m){$('#monsterEmoji').textContent=m.emoji;$('#monsterName').textContent=m.name;$('#monsterLore').textContent=m.lore;$('#rarity').textContent=m.rarity;['power','chaos','luck','aura'].forEach((x,i)=>$('#'+x).textContent=m.stats[i]);show('result')}
