const $=s=>document.querySelector(s);const screens=['home','create','result','battle','fusion'];let monster=null,opponent=null;
const emojis=['🦝','🦈','🐸','🦆','🦑','🐲','🦄','🍌','🧃','🦖','🐙','🥔','👽','🧠','🦀','🌚'];const traits=['SUPREMO','NINJA','DESTROYER','GOBLIN','WARRIOR','BOSS','PROPHET','MENACE','OVERLORD','CHAOS'];const lore=['escaped from a suspicious supermarket at 3AM.','was banned from three dimensions for excessive aura.','has one mission: become ridiculously famous.','looks harmless. It is absolutely not.','was created by accident and refuses to apologize.','has never lost an argument with a vending machine.'];
function show(id){screens.forEach(x=>$('#'+x)?.classList.toggle('active',x===id));scrollTo(0,0)}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h)}
function makeMonster(raw, salt=''){const h=hash(raw+salt);const stats=[55+h%46,50+(h>>3)%51,45+(h>>6)%56,55+(h>>9)%46];const power=Math.round(stats.reduce((a,b)=>a+b,0)/4);return{name:(['TURBO','LORD','CAPTAIN','PROFESSOR','KING','GENERAL'][h%6]+' '+traits[Math.floor(h/11)%traits.length]),emoji:emojis[h%emojis.length],lore:lore[h%lore.length],stats,rarity:power>90?'MYTHIC':power>78?'LEGENDARY':power>65?'EPIC':'UNCOMMON',power,seed:h,raw}}
function render(m){monster=m;$('#monsterEmoji').textContent=m.emoji;$('#monsterName').textContent=m.name;$('#monsterLore').textContent=m.lore;$('#rarity').textContent=m.rarity;['power','chaos','luck','aura'].forEach((x,i)=>$('#'+x).textContent=i===0?m.power:m.stats[i]);$('#battleEmoji').textContent=m.emoji;$('#battleName').textContent=m.name;$('#battlePower').textContent='POWER '+m.power}
function generate(){const raw=$('#nameInput').value.trim()||'Anonymous';render(makeMonster(raw));show('result')}
$('#createBtn').onclick=()=>show('create');$('#generateBtn').onclick=generate;document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>show('home'));
function encode(m){return btoa(unescape(encodeURIComponent(JSON.stringify(m)))).replace(/=/g,'')}
function challengeUrl(m){return location.href.split('#')[0]+'#challenge='+encode(m)}
$('#challengeBtn').onclick=()=>{if(!monster)return;const url=challengeUrl(monster);$('#shareUrl').textContent=url;show('battle')}
$('#shareBtn').onclick=async()=>{if(!monster)return;const url=challengeUrl(monster);const text=`I created ${monster.name} ${monster.emoji} — POWER ${monster.power}. Can you beat my monster?`;if(navigator.share){try{await navigator.share({title:'WHO ARE YOU?',text,url})}catch{}}else{await navigator.clipboard?.writeText(text+' '+url);$('#shareBtn').textContent='COPIED ✓';setTimeout(()=>$('#shareBtn').textContent='↗ SHARE MY MONSTER',1600)}};
$('#copyBtn').onclick=async()=>{await navigator.clipboard?.writeText($('#shareUrl').textContent);$('#copyBtn').textContent='COPIED ✓';setTimeout(()=>$('#copyBtn').textContent='COPY CHALLENGE LINK 🔗',1600)};
function battle(a,b){const scoreA=a.power+(a.seed%17);const scoreB=b.power+(b.seed%17);return scoreA>=scoreB?{winner:a,loser:b,margin:scoreA-scoreB}:{winner:b,loser:a,margin:scoreB-scoreA}}
function renderBattleResult(a,b){const r=battle(a,b);$('#battleResult').innerHTML=`<div class="winner">${r.winner.emoji}</div><div class="win-title">${r.winner.name} WINS</div><p>${r.winner.power} power vs ${r.loser.power} · victory margin ${r.margin}</p><div class="result-actions"><button class="primary wide" id="rematchBtn">⚔️ REMATCH</button><button class="secondary wide" id="fusionBtn">🧬 FUSE THESE MONSTERS</button></div>`;$('#rematchBtn').onclick=()=>renderBattleResult(b,a);$('#fusionBtn').onclick=()=>fuse(a,b);}
function fuse(a,b){const seed=hash(a.name+b.name);const f=makeMonster(a.name.slice(0,7)+b.name.slice(0,7),String(seed));f.name=''+a.name.split(' ')[0]+' × '+b.name.split(' ')[0];f.emoji=emojis[seed%emojis.length]+' '+emojis[(seed>>4)%emojis.length];f.power=Math.min(100,Math.round((a.power+b.power)/2+5));f.rarity=f.power>92?'MYTHIC FUSION':f.power>80?'LEGENDARY FUSION':'EPIC FUSION';$('#fusionEmoji').textContent=f.emoji;$('#fusionName').textContent=f.name;$('#fusionPower').textContent='POWER '+f.power;$('#fusionRarity').textContent=f.rarity;monster=f;show('fusion')}
function openBattle(){if(!monster)return;opponent=makeMonster('Unknown Challenger',String(Date.now()));$('#battleLeft').textContent=monster.emoji;$('#battleLeftName').textContent=monster.name;$('#battleLeftPower').textContent='POWER '+monster.power;$('#battleRight').textContent=opponent.emoji;$('#battleRightName').textContent=opponent.name;$('#battleRightPower').textContent='POWER '+opponent.power;renderBattleResult(monster,opponent);show('battle')}
function openShared(m){render(m);$('#sharedHint').textContent='Someone challenged you. Make your own monster and see who wins.';show('result')}
const params=location.hash;if(params.startsWith('#challenge=')){try{openShared(JSON.parse(decodeURIComponent(escape(atob(params.slice(11))))))}catch{}}
