(() => {
  const $ = s => document.querySelector(s);
  const screens = ['home','create','challenge','result','battle','fusion','leaderboard','collection'];
  const URL_BASE = () => location.href.split('#')[0];
  const playerId = localStorage.getItem('who_player_id') || (crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2));
  localStorage.setItem('who_player_id', playerId);
  const KEY = window.SUPABASE_PUBLISHABLE_KEY || '';
  const SUPABASE_URL = 'https://pbouvkzalxeragrpsotl.supabase.co';
  let db, channel, monster, room, incoming, muted = false, running = false;
  const emojis=['🦝','🦈','🐸','🦆','🦑','🐲','🦄','🍌','🧃','🦖','🐙','🥔','👽','🧠','🦀','🌚'];
  const traits=['SUPREMO','NINJA','DESTROYER','GOBLIN','WARRIOR','BOSS','PROPHET','MENACE','OVERLORD','CHAOS'];
  const lore=['escaped from a suspicious supermarket at 3AM.','was banned from three dimensions for excessive aura.','has one mission: become ridiculously famous.','looks harmless. It is absolutely not.','was created by accident and refuses to apologize.','has never lost an argument with a vending machine.'];
  const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h)};
  const today=()=>new Date().toISOString().slice(0,10);
  const makeMonster=(raw,salt='')=>{const h=hash(raw+salt),stats=[55+h%46,50+(h>>3)%51,45+(h>>6)%56,55+(h>>9)%46],power=Math.round(stats.reduce((a,b)=>a+b,0)/4);return{name:(['TURBO','LORD','CAPTAIN','PROFESSOR','KING','GENERAL'][h%6]+' '+traits[Math.floor(h/11)%traits.length]),emoji:emojis[h%emojis.length],lore:lore[h%lore.length],stats,rarity:power>90?'MYTHIC':power>78?'LEGENDARY':power>65?'EPIC':'UNCOMMON',power,seed:h,raw}};
  const avatar=m=>{const h=m?.seed||hash(m?.name||'monster'),h1=h%360,h2=(h>>7)%360,e=(h>>13)%3;const eyes=e===0?'<circle cx="70" cy="82" r="8"/><circle cx="110" cy="82" r="8"/>':e===1?'<path d="M60 82Q70 72 80 82Q70 92 60 82M100 82Q110 72 120 82Q110 92 100 82"/>':'<rect x="61" y="75" width="17" height="14" rx="5"/><rect x="102" y="75" width="17" height="14" rx="5"/>';return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 180 180"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="hsl(${h1} 85% 60%)"/><stop offset="1" stop-color="hsl(${h2} 85% 38%)"/></linearGradient></defs><rect width="180" height="180" rx="44" fill="#0c0c10"/><circle cx="90" cy="90" r="65" fill="url(#g)"/><ellipse cx="90" cy="101" rx="50" ry="43" fill="#17171c"/><path d="M55 48L49 12L70 38ZM125 48L131 12L110 38Z"/><g fill="#fff">${eyes}</g><path d="M70 113Q90 130 110 113" fill="none" stroke="#fff" stroke-width="6" stroke-linecap="round"/><circle cx="90" cy="99" r="5" fill="#ff4ecd"/></svg>`)};
  const setAvatar=(el,m)=>{if(el)el.innerHTML=`<img class="monster-avatar" src="${avatar(m)}" alt="${m?.name||'Monster'}">`};
  const show=id=>{screens.forEach(x=>$('#'+x)?.classList.toggle('active',x===id));scrollTo(0,0);if(id==='leaderboard')loadLeaderboard();if(id==='home')loadLeaderboard('daily','leaderboardHome');if(id==='collection')loadCollection()};
  const supa=()=>{if(!KEY)throw Error('Supabase publishable key missing');return db ||= window.supabase.createClient(SUPABASE_URL,KEY)};
  const enc=s=>btoa(unescape(encodeURIComponent(JSON.stringify(s)))).replace(/=/g,'');
  const dec=s=>JSON.parse(decodeURIComponent(escape(atob(s))));
  const challengeUrl=(m,code)=>URL_BASE()+'#challenge='+enc({...m,roomCode:code||''});
  const shortUrl=code=>URL_BASE()+'#c='+encodeURIComponent(code);
  const play=(f=440,d=.08,t='sine')=>{if(muted)return;try{const C=window.AudioContext||window.webkitAudioContext;const c=window.__audio||(window.__audio=new C()),o=c.createOscillator(),g=c.createGain();o.type=t;o.frequency.value=f;g.gain.value=.035;o.connect(g);g.connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.stop(c.currentTime+d)}catch{}};
  const sound=k=>{if(k==='hit'){play(120,.12,'sawtooth');setTimeout(()=>play(70,.08,'square'),45)}else if(k==='win'){[523,659,784,1046].forEach((f,i)=>setTimeout(()=>play(f,.13),i*90))}else if(k==='lose')play(150,.3,'sawtooth');else play(k==='count'?420:520,.1,'square')};
  function render(m){monster=m;setAvatar($('#monsterEmoji'),m);$('#monsterName').textContent=m.name;$('#monsterLore').textContent=m.lore;$('#rarity').textContent=m.rarity;['power','chaos','luck','aura'].forEach((x,i)=>$('#'+x).textContent=i?m.stats[i]:m.power);$('#streakValue').textContent=localStorage.getItem('who_streak')||0}
  function save(m){const a=JSON.parse(localStorage.getItem('who_collection')||'[]');if(!a.some(x=>x.seed===m.seed))a.unshift(m);localStorage.setItem('who_collection',JSON.stringify(a.slice(0,50)))}
  function loadCollection(){const e=$('#collectionList');if(!e)return;const a=JSON.parse(localStorage.getItem('who_collection')||'[]');e.innerHTML=a.length?a.map(x=>`<div class="rank"><img class="mini-avatar" src="${avatar(x)}"><span>${x.name}</span><small>⚡ ${x.power} · ${x.rarity}</small></div>`).join(''):'No monsters saved yet.'}
  function createRoom(){if(!monster)return;try{supa().from('game_battles').insert({code:Math.random().toString(36).slice(2,8).toUpperCase(),creator:monster,creator_id:playerId,status:'waiting',day:today()}).select().single().then(({data,error})=>{if(error||!data)throw error||Error();room=data;$('#shareUrl').textContent=shortUrl(data.code);$('#battleStatus').textContent='WAITING FOR YOUR FRIEND…';show('battle');subscribe(data.code)}).catch(()=>alert('Could not create the battle. Check Supabase table/RLS.'))}catch{alert('Battle needs the Supabase publishable key.')}}
  function subscribe(code){if(channel)db.removeChannel(channel);channel=supa().channel('battle:'+code).on('postgres_changes',{event:'UPDATE',schema:'public',table:'game_battles',filter:'code=eq.'+code},p=>{room=p.new;if(room?.creator&&room?.opponent)startBattle(room)}).subscribe()}
  async function join(code){try{const {data,error}=await supa().from('game_battles').select('*').eq('code',code).maybeSingle();if(error||!data||data.status==='finished'||data.opponent)throw Error();const mine=monster||makeMonster('Challenger',String(Date.now()));const r=await supa().from('game_battles').update({opponent:mine,opponent_id:playerId,status:'ready'}).eq('code',code).eq('status','waiting').is('opponent',null).select().single();if(r.error||!r.data)throw Error();room=r.data;show('battle');startBattle(room);subscribe(code)}catch{alert('This battle is unavailable, full, or expired.')}}
  function hpUI(){for(const id of ['battleLeft','battleRight']){const f=$('#'+id)?.closest('.fighter');if(f&&!f.querySelector('.hp-wrap'))f.insertAdjacentHTML('beforeend','<div class="hp-wrap"><div class="hp-label"><span>HP</span><b class="hp-value">100</b></div><div class="hp-track"><i class="hp-fill" style="width:100%"></i></div></div>')}}
  function setHP(id,v){const f=$('#'+id)?.closest('.fighter');if(!f)return;f.querySelector('.hp-fill').style.width=Math.max(0,v)+'%';f.querySelector('.hp-value').textContent=Math.round(Math.max(0,v))}
  function attackAnim(id,hit=false){const e=$('#'+id)?.closest('.fighter');if(!e)return;e.classList.remove('attacker','defender','fight-hit','fight-ko');void e.offsetWidth;e.classList.add(hit?'fight-hit':'attacker');setTimeout(()=>e.classList.remove('attacker','fight-hit'),500)}
  function startBattle(r){if(running||!r?.creator||!r?.opponent)return;running=true;hpUI();setAvatar($('#battleLeft'),r.creator);setAvatar($('#battleRight'),r.opponent);$('#battleLeftName').textContent=r.creator.name;$('#battleRightName').textContent=r.opponent.name;$('#battleLeftPower').textContent='POWER '+r.creator.power;$('#battleRightPower').textContent='POWER '+r.opponent.power;$('#battleStatus').textContent='BATTLE IN PROGRESS';let l=100,rr=100,turn=0;const winner=r.winner||((r.creator.power+(r.creator.seed%17)) >= (r.opponent.power+(r.opponent.seed%17))?r.creator:r.opponent);const timer=setInterval(()=>{turn++;const leftAttacks=turn%2===1,damage=14+(turn%3)*7;if(leftAttacks){rr-=damage;attackAnim('battleLeft');setTimeout(()=>attackAnim('battleRight',true),120)}else{l-=damage;attackAnim('battleRight');setTimeout(()=>attackAnim('battleLeft',true),120)}setHP('battleLeft',l);setHP('battleRight',rr);$('#battleResult').innerHTML=`<div class="round-badge">ROUND ${turn}</div><div class="damage-pop">-${damage}</div><p>${leftAttacks?r.creator.name:r.opponent.name} ATTACKS!</p>`;sound('hit');if(turn>=6){clearInterval(timer);const winLeft=winner.name===r.creator.name;l=winLeft?Math.max(22,l):0;rr=winLeft?0:Math.max(22,rr);setHP('battleLeft',l);setHP('battleRight',rr);const result={winner,loser:winLeft?r.opponent:r.creator,margin:Math.abs(winner.power-(winLeft?r.opponent:r.creator).power)};setTimeout(()=>finish(r,result),700)}},750);$('#battleResult').innerHTML='<div class="countdown big">3</div>';sound('count');setTimeout(()=>{$('#battleResult').innerHTML='<div class="countdown big">2</div>';sound('count')},650);setTimeout(()=>{$('#battleResult').innerHTML='<div class="countdown big">1</div>';sound('count')},1300);setTimeout(()=>{$('#battleResult').innerHTML='<div class="fight-now huge">FIGHT!</div>';sound('fight')},1950)}
  async function finish(r,result){if(!r||r.status==='finished')return;let saved=r;if(r.creator_id===playerId){const u=await supa().from('game_battles').update({status:'finished',winner:result.winner,finished_at:new Date().toISOString()}).eq('code',r.code).eq('creator_id',playerId).neq('status','finished').select().maybeSingle();if(u.data)saved=u.data}renderResult(saved,result)}
  function renderResult(r,result){const localWon=(result.winner?.name===monster?.name && ((r.creator_id===playerId)||(r.opponent_id===playerId)));if(localWon){let s=Number(localStorage.getItem('who_streak')||0);const last=localStorage.getItem('who_last_win'),d=new Date();d.setUTCDate(d.getUTCDate()-1);s=last===d.toISOString().slice(0,10)?s+1:1;localStorage.setItem('who_streak',s);localStorage.setItem('who_last_win',today());save(monster)};$('#battleStatus').textContent=localWon?'VICTORY':'DEFEAT';$('#battleResult').innerHTML=`<div class="winner"><img class="winner-avatar" src="${avatar(result.winner)}"></div><div class="win-title ${localWon?'you-win':'you-lose'}">${localWon?'YOU WIN 🏆':'YOU LOST 💀'}</div><p><b>${result.winner.name}</b> wins with ${result.winner.power} power · margin ${result.margin}</p><div class="streak-box">🔥 WIN STREAK <b>${localStorage.getItem('who_streak')||0}</b></div><button class="primary wide" id="rematchBtn">🔄 REMATCH</button><button class="secondary wide" id="shareResultBtn">↗ SHARE RESULT</button>`;sound(localWon?'win':'lose');running=false;$('#rematchBtn').onclick=()=>{show('create');$('#nameInput').value=''};$('#shareResultBtn').onclick=()=>navigator.share?navigator.share({title:'WHO ARE YOU?',text:`${localWon?'I WON 🏆':'I LOST 💀'} — ${result.winner.name} wins!`,url:shortUrl(r.code)}):navigator.clipboard?.writeText(shortUrl(r.code))}
  function openChallenge(m){incoming=m;setAvatar($('#challengeEmoji'),m);$('#challengeName').textContent=m.name;$('#challengeLore').textContent=m.lore;$('#challengePower').textContent=m.power;$('#challengeRarity').textContent=m.rarity;show('challenge')}
  async function loadLeaderboard(mode='all',target='leaderboardList'){const e=$('#'+target);if(!e)return;try{let q=supa().from('game_battles').select('winner,finished_at').eq('status','finished').order('finished_at',{ascending:false}).limit(500);if(mode==='daily')q=q.gte('finished_at',today()+'T00:00:00Z');const {data,error}=await q;if(error)throw error;const map={};(data||[]).forEach(b=>{const w=b.winner;if(!w)return;const n=w.name||'UNKNOWN';map[n]??={name:n,power:w.power||0,seed:w.seed||hash(n),wins:0};map[n].wins++;map[n].power=Math.max(map[n].power,w.power||0)});const rows=Object.values(map).sort((a,b)=>b.wins-a.wins||b.power-a.power).slice(0,10);e.innerHTML=rows.length?rows.map(x=>`<div class="rank"><img class="mini-avatar" src="${avatar(x)}"><span>${x.name}</span><small>🏆 ${x.wins} · ⚡ ${x.power}</small></div>`).join(''):'No battles yet — be the first.'}catch{e.textContent='Leaderboard unavailable right now.'}}
  function fuse(a,b){const f=makeMonster(a.name+b.name);f.name=a.name.split(' ')[0]+' × '+b.name.split(' ')[0];f.power=Math.min(100,Math.round((a.power+b.power)/2+5));f.rarity=f.power>92?'MYTHIC FUSION':f.power>80?'LEGENDARY FUSION':'EPIC FUSION';setAvatar($('#fusionEmoji'),f);$('#fusionName').textContent=f.name;$('#fusionPower').textContent='POWER '+f.power;$('#fusionRarity').textContent=f.rarity;save(f);monster=f;show('fusion')}
  window.renderFight=startBattle;window.finishBattle=finish;window.show=show;window.createRoom=createRoom;window.joinRoom=join;window.fuse=fuse;
  function bind(){
    $('#createBtn')?.addEventListener('click',()=>show('create'));$('#generateBtn')?.addEventListener('click',()=>{const n=$('#nameInput').value.trim();if(!n)return $('#nameInput').focus();render(makeMonster(n));show('result')});
    document.querySelectorAll('[data-home]').forEach(b=>b.addEventListener('click',()=>show('home')));$('#challengeBtn')?.addEventListener('click',createRoom);$('#acceptChallengeBtn')?.addEventListener('click',()=>{if(incoming?.roomCode)join(incoming.roomCode);else alert('This challenge has no live room code.')});$('#challengeShareBtn')?.addEventListener('click',()=>navigator.share?navigator.share({title:'WHO ARE YOU?',url:challengeUrl(incoming,incoming?.roomCode)}):navigator.clipboard?.writeText(challengeUrl(incoming,incoming?.roomCode)));$('#shareBtn')?.addEventListener('click',()=>navigator.share?navigator.share({title:'WHO ARE YOU?',text:monster?.name,url:challengeUrl(monster)}):navigator.clipboard?.writeText(challengeUrl(monster)));$('#collectionBtn')?.addEventListener('click',()=>{save(monster);loadCollection()});$('#openLeaderboard')?.addEventListener('click',()=>show('leaderboard'));$('#copyBtn')?.addEventListener('click',()=>navigator.clipboard?.writeText(shortUrl(room?.code||'')));$('#dailyTab')?.addEventListener('click',()=>loadLeaderboard('daily'));$('#allTab')?.addEventListener('click',()=>loadLeaderboard('all'));const t=document.createElement('button');t.className='sound-toggle';t.textContent='🔊 SOUND';t.onclick=()=>{muted=!muted;t.textContent=muted?'🔇 MUTE':'🔊 SOUND'};$('.topbar')?.appendChild(t);
    const h=location.hash;if(h.startsWith('#challenge=')){try{openChallenge(dec(h.slice(11)))}catch{}}else if(h.startsWith('#c=')){setTimeout(()=>join(decodeURIComponent(h.slice(3))),400)}else show('home');
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();