(()=>{
  const THREE_URL='https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.module.js';
  const state={ready:false,renderer:null,scene:null,camera:null,clock:null,raf:0,left:null,right:null};
  const load=()=>import(THREE_URL).then(T=>{state.T=T;init(T);hook()}).catch(()=>{});
  function init(T){const host=document.querySelector('.battle');if(!host||document.querySelector('#battle3d'))return;const wrap=document.createElement('div');wrap.id='battle3d';wrap.style.cssText='width:100%;height:300px;border-radius:24px;overflow:hidden;margin:18px 0;background:#08090d;position:relative';host.insertBefore(wrap,document.querySelector('#shareUrl'));const scene=new T.Scene();scene.background=new T.Color(0x08090d);state.scene=scene;state.clock=new T.Clock();const camera=new T.PerspectiveCamera(42,wrap.clientWidth/wrap.clientHeight,.1,100);camera.position.set(0,2.2,8);camera.lookAt(0,1,0);state.camera=camera;const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(wrap.clientWidth,wrap.clientHeight);scene.add(new T.HemisphereLight(0xffffff,0x202030,2.2));const key=new T.DirectionalLight(0xffffff,3);key.position.set(2,6,5);scene.add(key);const floor=new T.Mesh(new T.CylinderGeometry(4.2,4.2,.25,64),new T.MeshStandardMaterial({color:0x171a22,metalness:.35,roughness:.55}));floor.position.y=-.15;scene.add(floor);scene.add(new T.GridHelper(8,16,0x4a4f62,0x252936));wrap.appendChild(renderer.domElement);state.renderer=renderer;new ResizeObserver(()=>{const w=wrap.clientWidth,h=wrap.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)}).observe(wrap);state.ready=true;animate()}
  function make(T,m,x){const g=new T.Group(),seed=m?.seed||1,hue=(seed%360)/360,mat=new T.MeshStandardMaterial({color:new T.Color().setHSL(hue,.75,.5),roughness:.45}),dark=new T.MeshStandardMaterial({color:0x17171c});const body=new T.Mesh(new T.SphereGeometry(.92,24,16),mat);body.scale.y=1.12;body.position.y=1.05;g.add(body);const head=new T.Mesh(new T.SphereGeometry(.7,24,16),mat);head.position.y=2.05;g.add(head);[-.25,.25].forEach(q=>{const e=new T.Mesh(new T.SphereGeometry(.09,12,8),new T.MeshBasicMaterial({color:0xffffff}));e.position.set(q,2.15,.64);g.add(e)});const mouth=new T.Mesh(new T.TorusGeometry(.2,.035,8,20,Math.PI),dark);mouth.rotation.x=Math.PI/2;mouth.position.set(0,1.82,.67);g.add(mouth);[-.55,.55].forEach(q=>{const l=new T.Mesh(new T.CapsuleGeometry(.17,.55,6,12),dark);l.position.set(q,.35,0);g.add(l)});g.position.x=x;g.userData.baseX=x;return g}
  function render(a,b){if(!state.ready||!a||!b)return;const T=state.T;if(state.left)state.scene.remove(state.left);if(state.right)state.scene.remove(state.right);state.left=make(T,a,-2);state.right=make(T,b,2);state.scene.add(state.left,state.right)}
  function attack(side){const m=side==='left'?state.left:state.right;if(!m)return;const x=m.userData.baseX,dir=side==='left'?1:-1;m.position.x=x+dir*.6;setTimeout(()=>{if(m)m.position.x=x},180)}
  function hook(){const old=window.renderFight;if(typeof old==='function'){window.renderFight=function(r){old(r);if(r?.creator&&r?.opponent){render(r.creator,r.opponent);setTimeout(()=>attack('left'),350);setTimeout(()=>attack('right'),900)}}}}
  function animate(){state.raf=requestAnimationFrame(animate);const t=state.clock.getElapsedTime();if(state.left){state.left.position.y=Math.sin(t*3)*.035;state.left.rotation.y=Math.sin(t)*.05}if(state.right){state.right.position.y=Math.sin(t*3+1)*.035;state.right.rotation.y=-Math.sin(t)*.05}state.renderer.render(state.scene,state.camera)}
  window.Battle3D={render,attack};load();
})();