(()=>{
  const THREE_URL='https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.module.js';
  const GLTF_URL='https://cdn.jsdelivr.net/npm/three@0.179.1/examples/jsm/loaders/GLTFLoader.js';
  const SKEL_URL='https://cdn.jsdelivr.net/npm/three@0.179.1/examples/jsm/utils/SkeletonUtils.js';
  const MODEL='https://threejs.org/examples/models/gltf/RobotExpressive/RobotExpressive.glb';
  const S={T:null,GLTF:null,SKEL:null,ready:false,scene:null,camera:null,renderer:null,clock:null,wrap:null,left:null,right:null,base:null,mixers:[],actions:new WeakMap()};
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  async function load(){try{const T=await import(THREE_URL),G=await import(GLTF_URL),K=await import(SKEL_URL);S.T=T;S.GLTF=G.GLTFLoader;S.SKEL=K;init(T);const gltf=await new S.GLTF().loadAsync(MODEL);S.base=gltf.scene;S.base.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.frustumCulled=true}});buildAnimations();hook();}catch(e){console.error('3D character load failed',e)}}
  function init(T){const host=document.querySelector('.battle');if(!host||document.querySelector('#battle3d'))return;const w=document.createElement('div');w.id='battle3d';w.style.cssText='width:100%;height:min(62vw,500px);min-height:320px;border-radius:28px;overflow:hidden;margin:18px 0;background:radial-gradient(circle at 50% 30%,#27324c,#05060a 72%);position:relative;box-shadow:0 24px 80px rgba(0,0,0,.45)';host.insertBefore(w,document.querySelector('#shareUrl'));S.wrap=w;S.scene=new T.Scene();S.clock=new T.Clock();S.camera=new T.PerspectiveCamera(38,w.clientWidth/w.clientHeight,.1,100);S.camera.position.set(0,2.7,10);S.camera.lookAt(0,1.55,0);S.renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});S.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.7));S.renderer.setSize(w.clientWidth,w.clientHeight);S.renderer.shadowMap.enabled=true;S.renderer.shadowMap.type=T.PCFSoftShadowMap;S.renderer.outputColorSpace=T.SRGBColorSpace;w.appendChild(S.renderer.domElement);S.scene.add(new T.HemisphereLight(0xdce5ff,0x11121b,2.2));const key=new T.DirectionalLight(0xffffff,4.2);key.position.set(3,7,6);key.castShadow=true;key.shadow.mapSize.set(1024,1024);S.scene.add(key);const rim=new T.PointLight(0x8da2ff,22,14);rim.position.set(0,4,-3);S.scene.add(rim);const floor=new T.Mesh(new T.CylinderGeometry(4.7,4.7,.3,64),new T.MeshStandardMaterial({color:0x121722,metalness:.5,roughness:.4}));floor.position.y=-.18;floor.receiveShadow=true;S.scene.add(floor);const ring=new T.Mesh(new T.TorusGeometry(3.65,.04,12,96),new T.MeshBasicMaterial({color:0x8293ff}));ring.rotation.x=Math.PI/2;ring.position.y=.03;S.scene.add(ring);new ResizeObserver(()=>resize()).observe(w);}
  function resize(){if(!S.wrap)return;const w=S.wrap.clientWidth,h=S.wrap.clientHeight;S.camera.aspect=w/h;S.camera.updateProjectionMatrix();S.renderer.setSize(w,h)}
  function buildAnimations(){if(!S.base)return;const clips=(S.base.animations||[]);S.base.userData.clips={};clips.forEach(c=>S.base.userData.clips[c.name]=c);S.ready=true}
  function cloneCharacter(m,x,flip){const T=S.T,g=S.SKEL.clone(m);g.position.set(x,0,0);g.rotation.y=flip?Math.PI:0;g.userData={baseX:x,flip};g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});const mixer=new T.AnimationMixer(g);S.mixers.push(mixer);const map=S.base.userData.clips||{};const actions={};Object.keys(map).forEach(n=>{actions[n]=mixer.clipAction(map[n])});g.userData.mixer=mixer;g.userData.actions=actions;g.userData.clipNames=Object.keys(map);const idle=findAction(actions,['Idle','Standing','Survey']);if(idle){idle.reset().fadeIn(.2).play()}return g}
  function findAction(actions,names){for(const n of names){const k=Object.keys(actions).find(x=>x.toLowerCase().includes(n.toLowerCase()));if(k)return actions[k]}return null}
  function customCombat(g,type){const mixer=g.userData.mixer;if(!mixer)return;const a=g.userData.actions;let clip;if(type==='attack')clip=findAction(a,['Jump','Running','Walking']);else if(type==='hit')clip=findAction(a,['Death','Jump']);else clip=findAction(a,['Dance','Standing']);if(clip){Object.values(a).forEach(x=>{if(x!==clip)x.fadeOut(.12)});clip.reset().setLoop(S.T.LoopOnce,1).clampWhenFinished=true;clip.fadeIn(.1).play();mixer.addEventListener('finished',function done(e){if(e.action===clip){clip.fadeOut(.15);const idle=findAction(a,['Idle','Standing','Survey']);if(idle)idle.reset().fadeIn(.15).play();mixer.removeEventListener('finished',done)}})}}
  function render(a,b){if(!S.ready||!a||!b)return;[S.left,S.right].forEach(g=>{if(g){S.scene.remove(g);g.userData?.mixer?.stopAllAction()}});S.mixers=[];S.left=cloneCharacter(S.base,-2.1,true);S.right=cloneCharacter(S.base,2.1,false);S.scene.add(S.left,S.right);applyIdentity(S.left,a);applyIdentity(S.right,b)}
  function applyIdentity(g,m){const seed=Number(m?.seed||1);g.scale.setScalar(.95+((seed%11)/100));g.userData.seed=seed;const hue=(seed%360)/360;g.traverse(o=>{if(o.isMesh&&o.material?.color){const c=o.material.color.clone();const hsl={h:0,s:0,l:0};c.getHSL(hsl);o.material=o.material.clone();o.material.color.setHSL((hsl.h*.65+hue*.35)%1,hsl.s,hsl.l)}})}
  function attack(side){const g=side==='left'?S.left:S.right;if(!g)return;customCombat(g,'attack');const base=g.userData.baseX,dir=side==='left'?1:-1,start=performance.now();const step=now=>{const p=clamp((now-start)/380,0,1),e=p<.5?p*2:2-p*2;g.position.x=base+dir*.55*e;if(p<1)requestAnimationFrame(step);else g.position.x=base};requestAnimationFrame(step)}
  function hit(side){customCombat(side==='left'?S.left:S.right,'hit')}
  function victory(side){customCombat(side==='left'?S.left:S.right,'victory')}
  function hook(){const old=window.renderFight;if(typeof old==='function'){window.renderFight=function(r){old(r);if(r?.creator&&r?.opponent){render(r.creator,r.opponent);setTimeout(()=>attack('left'),500);setTimeout(()=>attack('right'),1200)}}}window.Battle3D={render,attack,hit,victory}}
  function animate(){requestAnimationFrame(animate);if(!S.renderer)return;const dt=S.clock.getDelta();S.mixers.forEach(m=>m.update(dt));S.renderer.render(S.scene,S.camera)}
  load().then(()=>animate());
})();