(()=>{
  const THREE_URL='https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.module.js';
  const S={ready:false,T:null,scene:null,camera:null,renderer:null,clock:null,wrap:null,left:null,right:null};
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const load=()=>import(THREE_URL).then(T=>{S.T=T;init(T);hook()}).catch(()=>{});
  function init(T){const host=document.querySelector('.battle');if(!host||document.querySelector('#battle3d'))return;const w=document.createElement('div');w.id='battle3d';w.style.cssText='width:100%;height:min(56vw,430px);min-height:300px;border-radius:28px;overflow:hidden;margin:18px 0;background:radial-gradient(circle at 50% 35%,#242b3f,#07080c 72%);position:relative;box-shadow:0 20px 60px rgba(0,0,0,.35)';host.insertBefore(w,document.querySelector('#shareUrl'));S.wrap=w;S.scene=new T.Scene();S.clock=new T.Clock();S.camera=new T.PerspectiveCamera(38,w.clientWidth/w.clientHeight,.1,100);S.camera.position.set(0,2.6,10);S.camera.lookAt(0,1.45,0);S.renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});S.renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.75));S.renderer.setSize(w.clientWidth,w.clientHeight);S.renderer.shadowMap.enabled=true;S.renderer.shadowMap.type=T.PCFSoftShadowMap;w.appendChild(S.renderer.domElement);S.scene.add(new T.HemisphereLight(0xcbd7ff,0x171421,2.1));const key=new T.DirectionalLight(0xffffff,4);key.position.set(3,7,6);key.castShadow=true;key.shadow.mapSize.set(1024,1024);S.scene.add(key);const rim=new T.PointLight(0x8ea1ff,18,12);rim.position.set(0,4,-2);S.scene.add(rim);const floor=new T.Mesh(new T.CylinderGeometry(4.6,4.6,.28,64),new T.MeshStandardMaterial({color:0x151923,metalness:.5,roughness:.42}));floor.position.y=-.18;floor.receiveShadow=true;S.scene.add(floor);const ring=new T.Mesh(new T.TorusGeometry(3.6,.035,10,96),new T.MeshBasicMaterial({color:0x7788ff}));ring.rotation.x=Math.PI/2;ring.position.y=.02;S.scene.add(ring);S.ready=true;new ResizeObserver(()=>resize()).observe(w);animate()}
  function resize(){if(!S.wrap||!S.renderer)return;const w=S.wrap.clientWidth,h=S.wrap.clientHeight;S.camera.aspect=w/h;S.camera.updateProjectionMatrix();S.renderer.setSize(w,h)}
  function material(T,c,rough=.48,metal=.08){return new T.MeshStandardMaterial({color:c,roughness:rough,metalness:metal})}
  function make(m,x,flip){const T=S.T,g=new T.Group(),seed=Number(m?.seed||1);const hue=((seed*47)%360)/360,base=new T.Color().setHSL(hue,.68,.48),dark=new T.Color().setHSL(hue,.35,.12),accent=new T.Color().setHSL((hue+.16)%1,.8,.62);const skin=material(T,base.getHex(),.42,.12),darkM=material(T,dark.getHex(),.5,.05),accentM=material(T,accent.getHex(),.3,.18),eyeM=new T.MeshStandardMaterial({color:0xffffff,emissive:0x9fb8ff,emissiveIntensity:1.6});
    const body=new T.Mesh(new T.SphereGeometry(.82,32,20),skin);body.scale.set(.95,1.18,.72);body.position.y=1.25;body.castShadow=true;g.add(body);
    const belly=new T.Mesh(new T.SphereGeometry(.58,24,16),accentM);belly.scale.set(1,.95,.35);belly.position.set(0,1.2,.62);belly.castShadow=true;g.add(belly);
    const head=new T.Mesh(new T.SphereGeometry(.68,32,20),skin);head.position.y=2.3;head.castShadow=true;g.add(head);
    const earGeo=new T.SphereGeometry(.25,20,14);[-1,1].forEach(s=>{const e=new T.Mesh(earGeo,accentM);e.position.set(s*.55,2.72,0);e.scale.set(1,.9,.55);e.castShadow=true;g.add(e)});
    [-.23,.23].forEach(q=>{const e=new T.Mesh(new T.SphereGeometry(.105,16,12),eyeM);e.position.set(q,2.38,.61);e.castShadow=true;g.add(e);const p=new T.Mesh(new T.SphereGeometry(.045,12,8),darkM);p.position.set(q,2.38,.705);g.add(p)});
    const hornCount=1+(seed%3);for(let i=0;i<hornCount;i++){const h=new T.Mesh(new T.ConeGeometry(.13,.48,16),accentM);h.position.set((i-(hornCount-1)/2)*.22,2.88,.02);h.rotation.z=(i-(hornCount-1)/2)*.18;h.castShadow=true;g.add(h)}
    const armGeo=new T.CapsuleGeometry(.16,.72,8,16);[-1,1].forEach(s=>{const a=new T.Mesh(armGeo,skin);a.position.set(s*.82,1.22,0);a.rotation.z=s*.45;a.castShadow=true;g.add(a)});
    const legGeo=new T.CapsuleGeometry(.19,.6,8,16);[-1,1].forEach(s=>{const l=new T.Mesh(legGeo,darkM);l.position.set(s*.34,.42,0);l.castShadow=true;g.add(l)});
    const tail=new T.Mesh(new T.TorusGeometry(.55,.14,12,24,Math.PI*1.35),accentM);tail.position.set(flip?.55:-.55,.85,-.25);tail.rotation.y=flip?-.8:.8;tail.castShadow=true;g.add(tail);
    const ring=new T.Mesh(new T.TorusGeometry(.95,.018,8,64),new T.MeshBasicMaterial({color:accent.getHex(),transparent:true,opacity:.65}));ring.rotation.x=Math.PI/2;ring.position.y=.04;g.add(ring);
    g.position.set(x,0,0);g.userData={baseX:x,flip,seed};return g}
  function render(a,b){if(!S.ready||!a||!b)return;[S.left,S.right].forEach(x=>x&&S.scene.remove(x));S.left=make(a,-2,true);S.right=make(b,2,false);S.scene.add(S.left,S.right)}
  function attack(side){const m=side==='left'?S.left:S.right;if(!m)return;const base=m.userData.baseX,dir=side==='left'?1:-1;const start=performance.now();const step=now=>{const p=clamp((now-start)/360,0,1),e=p<.5?p*2:2-p*2;m.position.x=base+dir*.72*e;m.rotation.z=dir*.08*Math.sin(p*Math.PI);if(p<1)requestAnimationFrame(step);else{m.position.x=base;m.rotation.z=0}};requestAnimationFrame(step)}
  function hook(){const old=window.renderFight;if(typeof old==='function'){window.renderFight=function(r){old(r);if(r?.creator&&r?.opponent){render(r.creator,r.opponent);setTimeout(()=>attack('left'),450);setTimeout(()=>attack('right'),1100)}}}}
  function animate(){requestAnimationFrame(animate);if(!S.renderer)return;const t=S.clock.getElapsedTime();if(S.left){S.left.position.y=Math.sin(t*2.2)*.035;S.left.rotation.y=Math.sin(t*.8)*.045}if(S.right){S.right.position.y=Math.sin(t*2.2+1)*.035;S.right.rotation.y=-Math.sin(t*.8)*.045}S.renderer.render(S.scene,S.camera)}
  window.Battle3D={render,attack};load();
})();