(()=>{
'use strict';
const S={T:null,loading:null,slots:new Map(),battle:null};
const getT=()=>{if(S.T)return Promise.resolve(S.T);if(S.loading)return S.loading;S.loading=import('https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.module.js').then(T=>{S.T=T;return T});return S.loading};
const rnd=seed=>{let x=(Number(seed)||1)>>>0;return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}};
const mat=(T,c,r=.5,m=.05,e=0)=>new T.MeshStandardMaterial({color:c,roughness:r,metalness:m,emissive:e?c:0,emissiveIntensity:e});
function build(T,m,small=false){const r=rnd(m?.seed||1),h=Math.floor(r()*360),base=new T.Color().setHSL(h/360,.65,.46),accent=new T.Color().setHSL(((h+35)%360)/360,.8,.6),dark=new T.Color().setHSL(h/360,.35,.13);const g=new T.Group();const skin=mat(T,base.getHex(),.4,.12),a=mat(T,accent.getHex(),.32,.2),d=mat(T,dark.getHex(),.55,.05),glow=mat(T,accent.getHex(),.25,.25,1.5);g.scale.setScalar(small?.72:1);g.userData.seed=m?.seed||1;
 const torso=new T.Mesh(new T.SphereGeometry(.72,24,16),skin);torso.scale.set(.92,1.2,.68);torso.position.y=1.25;g.add(torso);const chest=new T.Mesh(new T.SphereGeometry(.42,20,14),a);chest.scale.set(1,.9,.35);chest.position.set(0,1.25,.57);g.add(chest);const head=new T.Mesh(new T.SphereGeometry(.62,24,16),skin);head.position.y=2.28;g.add(head);const helmet=new T.Mesh(new T.SphereGeometry(.67,24,12,0,Math.PI*2,0,Math.PI*.52),d);helmet.position.y=2.38;g.add(helmet);
 const eyeMat=mat(T,0xffffff,.2,.05,2);[-.2,.2].forEach(x=>{const eye=new T.Mesh(new T.SphereGeometry(.095,12,8),eyeMat);eye.position.set(x,2.3,.56);g.add(eye)});const horns=1+Math.floor(r()*3);for(let i=0;i<horns;i++){const horn=new T.Mesh(new T.ConeGeometry(.11,.4+r()*.25,12),a);horn.position.set((i-(horns-1)/2)*.25,2.82,.02);horn.rotation.z=(i-(horns-1)/2)*.15;g.add(horn)}
 const armG=new T.CapsuleGeometry(.15,.62,6,12);[-1,1].forEach(side=>{const arm=new T.Mesh(armG,skin);arm.position.set(side*.78,1.35,0);arm.rotation.z=side*(.28+r()*.35);g.add(arm);const fist=new T.Mesh(new T.SphereGeometry(.2,16,10),a);fist.position.set(side*1.02,.92,0);g.add(fist)});const legG=new T.CapsuleGeometry(.18,.62,6,12);[-1,1].forEach(side=>{const leg=new T.Mesh(legG,d);leg.position.set(side*.3,.43,0);g.add(leg);const boot=new T.Mesh(new T.SphereGeometry(.23,16,10),a);boot.scale.set(1.2,.65,1.5);boot.position.set(side*.3,.08,.12);g.add(boot)});
 const tail=new T.Mesh(new T.TorusGeometry(.52,.11,10,20,Math.PI*1.25),a);tail.position.set(r()>.5?.55:-.55,.9,-.25);tail.rotation.y=r()>.5?-.8:.8;g.add(tail);const ring=new T.Mesh(new T.TorusGeometry(1,.018,8,48),glow);ring.rotation.x=Math.PI/2;ring.position.y=.03;g.add(ring);g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});return g}
function sceneFor(host,T,battle=false){const scene=new T.Scene(),camera=new T.PerspectiveCamera(battle?38:32,1,.1,100),renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.setSize(Math.max(1,host.clientWidth),Math.max(1,host.clientHeight),false);host.innerHTML='';host.appendChild(renderer.domElement);scene.add(new T.HemisphereLight(0xeaf0ff,0x10121a,2.2));const light=new T.DirectionalLight(0xffffff,3.4);light.position.set(3,6,5);light.castShadow=true;scene.add(light);return {scene,camera,renderer}}
function resize(ctx,host){const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);ctx.camera.aspect=w/h;ctx.camera.updateProjectionMatrix();ctx.renderer.setSize(w,h,false)}
async function setSlot(selector,m){const host=document.querySelector(selector);if(!host)return;const T=await getT();const ctx=sceneFor(host,T);const g=build(T,m,true);ctx.scene.add(g);ctx.camera.position.set(0,1.65,5);ctx.camera.lookAt(0,1.25,0);resize(ctx,host);new ResizeObserver(()=>resize(ctx,host)).observe(host);let last=performance.now();const loop=now=>{const dt=Math.min(.05,(now-last)/1000);last=now;g.rotation.y+=dt*.35;g.position.y=Math.sin(now*.0022)*.035;ctx.renderer.render(ctx.scene,ctx.camera);requestAnimationFrame(loop)};requestAnimationFrame(loop);S.slots.set(selector,{ctx,g})}
async function renderBattle(a,b){const host=document.querySelector('#battle3d');if(!host||!a||!b)return;const T=await getT();const ctx=sceneFor(host,T,true);const floor=new T.Mesh(new T.CylinderGeometry(4.5,4.5,.25,64),mat(T,0x121722,.4,.5));floor.position.y=-.15;ctx.scene.add(floor);const ring=new T.Mesh(new T.TorusGeometry(3.5,.035,10,80),new T.MeshBasicMaterial({color:0x8797ff}));ring.rotation.x=Math.PI/2;ring.position.y=.01;ctx.scene.add(ring);const L=build(T,a),R=build(T,b);L.position.x=-2.05;R.position.x=2.05;R.rotation.y=Math.PI;ctx.scene.add(L,R);ctx.camera.position.set(0,2.45,9.8);ctx.camera.lookAt(0,1.35,0);resize(ctx,host);new ResizeObserver(()=>resize(ctx,host)).observe(host);S.battle={ctx,left:{g:L,base:-2.05},right:{g:R,base:2.05}};let last=performance.now();const loop=now=>{if(!S.battle)return;last=now;L.position.y=Math.sin(now*.0022)*.04;R.position.y=Math.sin(now*.0022+1)*.04;ctx.renderer.render(ctx.scene,ctx.camera);requestAnimationFrame(loop)};requestAnimationFrame(loop)}
function play(name,side){const b=S.battle;if(!b)return;const x=side==='left'?b.left:b.right,dir=side==='left'?1:-1,base=x.base,start=performance.now(),duration=name==='attack'?420:name==='hit'?300:700;const loop=now=>{const p=Math.min(1,(now-start)/duration),e=p<.5?p*2:2-p*2;if(name==='attack')x.g.position.x=base+dir*.75*e;else if(name==='hit')x.g.position.x=base-dir*.25*e;else if(name==='victory')x.g.position.y=.15+Math.abs(Math.sin(p*Math.PI*3))*.18;else if(name==='defeat')x.g.rotation.z=dir*.55*p;if(p<1)requestAnimationFrame(loop);else{x.g.position.x=base;x.g.position.y=0;x.g.rotation.z=0}};requestAnimationFrame(loop)}
window.Character3D={setSlot,renderBattle,play};
})();