(()=>{
'use strict';
const S={T:null,loading:null,battle:null,slots:new Map()};
const THREE_URL='https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const rand=seed=>{let x=(Number(seed)>>>0)||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}};
const pick=(r,a)=>a[Math.floor(r()*a.length)];
async function getT(){if(S.T)return S.T;if(!S.loading)S.loading=import(THREE_URL).then(m=>(S.T=m,m)).catch(e=>{S.loading=null;throw e});return S.loading}
const M=(T,c,r=.5,me=.05,e=0)=>new T.MeshStandardMaterial({color:c,roughness:r,metalness:me,emissive:e?c:0,emissiveIntensity:e});
function part(T,geo,mat,x,y,z){const m=new T.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;return m}
function makeCharacter(T,seed,scale=1){
 const r=rand(seed),g=new T.Group();
 const hue=r(), skin=new T.Color().setHSL(hue,.62,.48), armor=new T.Color().setHSL((hue+.08+r()*.22)%1,.76,.30), accent=new T.Color().setHSL((hue+.45+r()*.15)%1,.9,.62), dark=new T.Color().setHSL(hue,.3,.08);
 const sm=M(T,skin.getHex(),.45,.08), am=M(T,armor.getHex(),.3,.3), xm=M(T,accent.getHex(),.25,.4), dm=M(T,dark.getHex(),.65,.05), glow=M(T,accent.getHex(),.2,.25,1.8);
 const bodyType=Math.floor(r()*5), headType=Math.floor(r()*4), armorType=Math.floor(r()*4), eyeType=Math.floor(r()*4), hornType=Math.floor(r()*5), weaponType=Math.floor(r()*4);
 const sx=[.72,1.05,1.3,.9,1.18][bodyType], sy=[1.15,.9,.78,1.35,1.0][bodyType], leg=[.55,.75,.48,.9,.65][bodyType];
 const torso=part(T,new T.SphereGeometry(.7,20,14),am,0,1.2,0);torso.scale.set(sx,sy,.58);g.add(torso);
 const belt=part(T,new T.TorusGeometry(.55*sx,.055,8,24),xm,0,1.0,0);belt.rotation.x=Math.PI/2;g.add(belt);
 const chest=part(T,new T.BoxGeometry(sx*(armorType===1?1.05:.9),.3,.16),armorType===2?xm:am,0,1.38,.55);g.add(chest);
 const headR=[.46,.58,.52,.42][headType];const head=part(T,new T.SphereGeometry(headR,24,18),sm,0,2.32,0);head.scale.set([1.15,.9,1.0,.82][headType],[.9,1.15,1,.82][headType],1);g.add(head);
 const eyeY=2.35,sep=.18+r()*.14,count=eyeType===3?3:2;for(let i=0;i<count;i++){const x=(i-(count-1)/2)*sep;const e=part(T,new T.SphereGeometry(.055+(r()*.035),12,8),glow,x,eyeY,.43);if(eyeType===1)e.scale.y=.45;if(eyeType===2)e.scale.x=1.7;g.add(e)}
 const mouth=part(T,new T.BoxGeometry(.16+r()*.2,.035,.04),dm,0,2.08,.47);mouth.scale.x=1+(headType*.12);g.add(mouth);
 const horns=hornType===0?0:hornType===1?2:hornType===2?4:hornType===3?1:2;for(let i=0;i<horns;i++){const side=i%2?-1:1, row=Math.floor(i/2), h=part(T,new T.ConeGeometry(.09+r()*.07,.35+r()*.35,10),xm,side*(.24+row*.13),2.7-row*.08,.02);h.rotation.z=side*(.15+r()*.3);g.add(h)}
 const ears=pick(r,['round','point','wide']);[-1,1].forEach(side=>{let e;if(ears==='point')e=part(T,new T.ConeGeometry(.17,.38,10),xm,side*.5,2.52,.02);else e=part(T,new T.SphereGeometry(.19,14,9),xm,side*.5,2.5,.02);e.scale.set(1,.8,ears==='wide'?1:.55);if(ears==='point')e.rotation.z=side*.35;g.add(e)});
 const armR=.12+r()*.09,armL=.5+r()*.42;[-1,1].forEach(side=>{const a=part(T,new T.CapsuleGeometry(armR,armL,7,12),sm,side*(sx*.75),1.28,0);a.rotation.z=side*(.18+r()*.35);g.add(a);g.add(part(T,new T.SphereGeometry(armR*1.35,12,8),am,side*(sx*.82),.93,0))});
 [-1,1].forEach(side=>{const l=part(T,new T.CapsuleGeometry(.15+r()*.06,leg,7,12),dm,side*(.22+r()*.1),.4,0);g.add(l);const b=part(T,new T.SphereGeometry(.25+r()*.08,14,9),am,side*(.22+r()*.1),.05,.1);b.scale.set(1.25,.55,1.5);g.add(b)});
 const tail=Math.floor(r()*4);if(tail){const t=part(T,new T.TorusGeometry(.35+r()*.25,.07+r()*.04,8,24,Math.PI*(.7+r()*1.1)),xm,(r()>.5?.5:-.5),.85,-.35);t.rotation.y=r()*1.2-.6;g.add(t)}
 const pack=part(T,new T.BoxGeometry(.45+r()*.3,.5+r()*.3,.2),dm,0,1.3,-.52);g.add(pack);
 const weapon=new T.Group();if(weaponType===0||weaponType===1){const blade=part(T,new T.BoxGeometry(.11,weaponType===0?.85:.58,.09),xm,0,.52,0);blade.rotation.z=weaponType===1?.38:0;weapon.add(blade);weapon.add(part(T,new T.BoxGeometry(.34,.07,.12),am,0,.1,0));weapon.add(part(T,new T.CylinderGeometry(.04,.05,.3,8),dm,0,-.08,0))}else if(weaponType===2){weapon.add(part(T,new T.CylinderGeometry(.04,.06,1.25,10),dm,0,.45,0));weapon.add(part(T,new T.SphereGeometry(.14,16,12),glow,0,1.1,0))}else{weapon.add(part(T,new T.BoxGeometry(.14,.7,.14),xm,0,.5,0));weapon.add(part(T,new T.SphereGeometry(.2,14,10),glow,0,.95,0))}weapon.position.set(.9,1.05,.12);weapon.rotation.z=-.35;g.add(weapon);
 const rarityRoll=r(),rarity=rarityRoll>.965?'LEGENDARY':rarityRoll>.82?'EPIC':rarityRoll>.52?'RARE':'COMMON';const aura=part(T,new T.TorusGeometry(1.05,.025,8,64),new T.MeshBasicMaterial({color:accent.getHex(),transparent:true,opacity:rarity==='LEGENDARY'?.95:rarity==='EPIC'?.75:.5}),0,.04,0);aura.rotation.x=Math.PI/2;g.add(aura);
 g.scale.setScalar(scale);g.userData={seed,bodyType,headType,armorType,eyeType,hornType,weaponType,rarity,phase:r()*Math.PI*2};return g;
}
function renderer(T,host){const old=host.querySelector('canvas');if(old)old.remove();const r=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});r.setPixelRatio(Math.min(window.devicePixelRatio||1,1.5));r.outputColorSpace=T.SRGBColorSpace;r.shadowMap.enabled=true;host.appendChild(r.domElement);return r}
function mount(host,seed,scale=.82){const T=S.T,scene=new T.Scene(),camera=new T.PerspectiveCamera(32,1,.1,100),ren=renderer(T,host);scene.add(new T.HemisphereLight(0xf4f7ff,0x10121b,2.4));const key=new T.DirectionalLight(0xffffff,3.8);key.position.set(3,6,5);key.castShadow=true;scene.add(key);const fill=new T.PointLight(0x8899ff,2.2,8);fill.position.set(-3,2,3);scene.add(fill);const floor=part(T,new T.CylinderGeometry(1.55,1.55,.08,40),M(T,0x101722,.65,.25),0,-.08,0);floor.receiveShadow=true;scene.add(floor);const c=makeCharacter(T,seed,scale);scene.add(c);camera.position.set(0,1.5,5);camera.lookAt(0,1.25,0);const resize=()=>{const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);camera.aspect=w/h;camera.updateProjectionMatrix();ren.setSize(w,h,false)};if(window.ResizeObserver)new ResizeObserver(resize).observe(host);resize();let alive=true;const loop=now=>{if(!alive)return;c.position.y=Math.sin(now*.0018+c.userData.phase)*.045;c.rotation.y=Math.sin(now*.0008+c.userData.phase)*.12;ren.render(scene,camera);requestAnimationFrame(loop)};requestAnimationFrame(loop);return()=>{alive=false;ren.dispose();scene.traverse(o=>{o.geometry?.dispose?.();if(o.material?.dispose)o.material.dispose()})}}
async function setSlot(selector,m){const host=document.querySelector(selector);if(!host)return;const key=selector+'|'+String(m?.seed||1);host.dataset.seed=String(m?.seed||1);host.innerHTML='<div class="character3d-loading">GENERATING FIGHTER</div>';try{const T=await getT();S.slots.get(selector)?.();const cleanup=mount(host,Number(m?.seed)||1,.82);S.slots.set(selector,cleanup)}catch(e){console.error('Character3D',e);host.innerHTML='<div class="character3d-error">3D unavailable</div>'}}
async function renderBattle(a,b){const host=document.querySelector('#battle3d');if(!host||!a||!b)return;host.innerHTML='<div class="character3d-loading">GENERATING ARENA</div>';try{const T=await getT();const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,Math.max(1,host.clientWidth)/Math.max(1,host.clientHeight),.1,100),ren=renderer(T,host);scene.add(new T.HemisphereLight(0xe7edff,0x0b0d14,2.6));const key=new T.DirectionalLight(0xffffff,4.8);key.position.set(4,7,6);key.castShadow=true;scene.add(key);const floor=part(T,new T.CylinderGeometry(4.6,4.6,.2,64),M(T,0x0f1622,.55,.35),0,-.12,0);floor.receiveShadow=true;scene.add(floor);const ring=part(T,new T.TorusGeometry(3.6,.04,10,96),new T.MeshBasicMaterial({color:0x6f86ff}),0,.02,0);ring.rotation.x=Math.PI/2;scene.add(ring);const L=makeCharacter(T,Number(a.seed)||1,.9),R=makeCharacter(T,Number(b.seed)||2,.9);L.position.x=-2;R.position.x=2;L.rotation.y=Math.PI;scene.add(L,R);camera.position.set(0,2.45,10);camera.lookAt(0,1.35,0);S.battle={L,R,scene,camera,renderer:ren};const resize=()=>{const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);camera.aspect=w/h;camera.updateProjectionMatrix();ren.setSize(w,h,false)};if(window.ResizeObserver)new ResizeObserver(resize).observe(host);resize();const loop=now=>{if(S.battle?.renderer!==ren)return;L.position.y=Math.sin(now*.002+L.userData.phase)*.04;R.position.y=Math.sin(now*.002+R.userData.phase)*.04;ren.render(scene,camera);requestAnimationFrame(loop)};requestAnimationFrame(loop)}catch(e){console.error('Battle3D',e);host.innerHTML='<div class="character3d-error">3D battle unavailable</div>'}}
function play(name,side){const b=S.battle;if(!b)return;const c=side==='right'?b.R:b.L;if(name==='attack'){const x=c.position.x,d=side==='right'?-1:1,t=performance.now();const step=n=>{const p=Math.min(1,(n-t)/360),e=p<.5?p*2:2-p*2;c.position.x=x+d*.7*e;if(p<1)requestAnimationFrame(step);else c.position.x=x};requestAnimationFrame(step)}else if(name==='hit'){const x=c.position.x,t=performance.now();const step=n=>{const p=Math.min(1,(n-t)/240);c.position.x=x+Math.sin(p*Math.PI*6)*(1-p)*.18;if(p<1)requestAnimationFrame(step);else c.position.x=x};requestAnimationFrame(step)}else if(name==='victory'){const y=c.position.y,t=performance.now();const step=n=>{const p=Math.min(1,(n-t)/900);c.position.y=y+Math.abs(Math.sin(p*Math.PI*3))*.28;c.rotation.y+=.035;if(p<1)requestAnimationFrame(step)};requestAnimationFrame(step)}else if(name==='defeat'){const y=c.position.y,t=performance.now();const step=n=>{const p=Math.min(1,(n-t)/650);c.rotation.z=p*1.35;c.position.y=y-p*.3;if(p<1)requestAnimationFrame(step)};requestAnimationFrame(step)}}
window.Character3D={setSlot,renderBattle,play};
})();