(()=>{
'use strict';
const SB_URL='https://pbouvkzalxeragrpsotl.supabase.co',KEY=window.SUPABASE_PUBLISHABLE_KEY||'';
const screens=['home','create','challenge','result','battle','fusion','leaderboard','collection'];
const PLAYER_KEY='who_player_id',ROOM_KEY='who_live_room_code',MONSTER_KEY='who_current_monster';
let db=null,monster=null,room=null,channel=null,poll=null,startTimer=null,lastRoomCode=null,booting=false;
const $=s=>document.querySelector(s),hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h)},today=()=>new Date().toISOString().slice(0,10);
const playerId=()=>{let v=localStorage.getItem(PLAYER_KEY);if(!v){v=crypto.randomUUID();localStorage.setItem(PLAYER_KEY,v)}return v};
const supa=()=>{if(!KEY)throw Error('Supabase key missing');return db||(db=window.supabase.createClient(SB_URL,KEY))};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function makeMonster(raw){const h=hash(String(raw||'Monster')),stats=[55+h%46,50+(h>>3)%51,45+(h>>6)%56,55+(h>>9)%46],power=Math.round(stats.reduce((a,b)=>a+b,0)/4);return{name:(['TURBO','LORD','CAPTAIN','PROFESSOR','KING','GENERAL'][h%6]+' '+['SUPREMO','NINJA','DESTROYER','GOBLIN','WARRIOR','BOSS','PROPHET','MENACE','OVERLORD','CHAOS'][Math.floor(h/11)%10]),lore:['escaped from a suspicious supermarket at 3AM.','was banned from three dimensions for excessive aura.','has one mission: become ridiculously famous.','looks harmless. It is absolutely not.','was created by accident and refuses to apologize.'][h%5],stats,rarity:power>90?'MYTHIC':power>78?'LEGENDARY':power>65?'EPIC':'UNCOMMON',power,seed:h,raw:String(raw||'Monster')}}
function saveMonster(m){monster=m;localStorage.setItem(MONSTER_KEY,JSON.stringify(m));return m}function loadMonster(){try{return JSON.parse(localStorage.getItem(MONSTER_KEY)||'null')}catch{return null}}
function show(id){screens.forEach(x=>$('#'+x)?.classList.toggle('active',x===id));window.scrollTo(0,0);if(id==='home'){loadLeaderboard('daily','leaderboardHome');mountHome3D()}if(id==='leaderboard')loadLeaderboard('all','leaderboardList');if(id==='collection')loadCollection();if(id==='battle')bootRoom();if(id==='result'&&monster)window.Character3D?.setSlot?.('#monster3d',monster)}window.show=show;
const setText=(id,v)=>{const e=$('#'+id);if(e)e.textContent=v};
function renderMonster(m){saveMonster(m);setText('monsterName',m.name);setText('monsterLore',m.lore);setText('rarity',m.rarity);setText('power',m.power);setText('chaos',m.stats[1]);setText('luck',m.stats[2]);setText('aura',m.stats[3]);setText('streakValue',localStorage.getItem('who_streak')||'0');window.Character3D?.setSlot?.('#monster3d',m)}
function setChallenge(m){setText('challengeRarity',m.rarity);setText('challengeName',m.name);setText('challengeLore',m.lore);setText('challengePower',m.power);window.Character3D?.setSlot?.('#challenge3d',m)}
function parseRoute(){const raw=location.hash||'';if(!raw)return{type:null,code:null,payload:null};const h=raw.slice(1);if(h.startsWith('c='))return{type:'room',code:safeCode(h.slice(2))};if(h.startsWith('room='))return{type:'room',code:safeCode(h.slice(5))};if(h.startsWith('battle='))return{type:'room',code:safeCode(h.slice(7))};if(h.startsWith('join='))return{type:'room',code:safeCode(h.slice(5))};if(h.startsWith('challenge=')){try{const b=decodeURIComponent(h.slice(10));const x=JSON.parse(decodeURIComponent(escape(atob(b))));return{type:'challenge',code:safeCode(x.roomCode||x.code||x.liveRoomCode||x.rootCode),payload:x}}catch{return{type:'challenge',code:null,payload:null}}}return{type:null,code:null,payload:null}}
function safeCode(v){try{v=decodeURIComponent(String(v||''))}catch{}v=String(v||'').trim().toUpperCase();return /^[A-Z0-9]{4,12}$/.test(v)?v:null}
function roomUrl(code){const u=new URL(location.href);u.hash='battle='+encodeURIComponent(code);return u.toString()}
function setRoom(r){room=r;if(r?.code){localStorage.setItem(ROOM_KEY,r.code);lastRoomCode=r.code}else{localStorage.removeItem(ROOM_KEY);lastRoomCode=null}}
const side=r=>r?.creator_id===playerId()?'creator':r?.opponent_id===playerId()?'opponent':null;
async function getRoom(code){code=safeCode(code||room?.code||parseRoute().code||localStorage.getItem(ROOM_KEY));if(!code)return null;const{data,error}=await supa().from('game_battles').select('*').eq('code',code).maybeSingle();if(error)throw error;return data||null}
function paintRoom(r){setRoom(r);if($('#shareUrl'))$('#shareUrl').textContent=r?.code?roomUrl(r.code):'';const a=r?.creator,b=r?.opponent;setText('battleLeftName',a?.name||'PLAYER 1');setText('battleLeftPower',a?`POWER ${a.power}`:'WAITING');setText('battleRightName',b?.name||'WAITING...');setText('battleRightPower',b?`POWER ${b.power}`:'WAITING');if(a&&b)window.Character3D?.renderBattle?.(a,b);ensureReadyUI();const panel=$('#readyRoomPanel');if(panel){const s=side(r),ar=!!a?.ready,br=!!b?.ready,both=!!a&&!!b;setText('readyRoomCode',r?.code?'ROOM '+r.code:'');const p=$('#readyPlayers');if(p)p.innerHTML=`<span>${ar?'READY':'NOT READY'} <b>${esc(a?.name||'Player 1')}</b></span><span>${br?'READY':'NOT READY'} <b>${esc(b?.name||'Player 2')}</b></span>`;const btn=$('#readyBtn');if(btn){const mine=s==='creator'?ar:s==='opponent'?br:false;btn.disabled=!s||!both||mine||r.status!=='waiting';btn.textContent=mine?'READY ✓':'I AM READY'}setText('readyHint',!both?'Waiting for the second player to join…':r.status==='starting'?'Both ready. Starting together…':r.status==='finished'?'Battle finished.':'Both players must press READY.')}}
function ensureReadyUI(){const b=document.querySelector('#battle .battle');if(!b||$('#readyRoomPanel'))return;const p=document.createElement('div');p.id='readyRoomPanel';p.innerHTML='<div class="ready-room-title">ROOM READY</div><div id="readyRoomCode" class="ready-room-code"></div><div id="readyPlayers" class="ready-players"></div><button id="readyBtn" class="primary wide" type="button">I AM READY</button><div id="readyHint" class="ready-hint">Waiting for both players…</div>';b.insertBefore(p,$('#shareUrl')||b.firstChild);$('#readyBtn').onclick=ready}
async function ready(){try{const r=await getRoom(room?.code);if(!r||r.status!=='waiting'||!r.creator||!r.opponent)return;const s=side(r);if(!s)return;const current=s==='creator'?r.creator:r.opponent;if(current?.ready)return;const mine={...current,ready:true,readyAt:Date.now()};const patch=s==='creator'?{creator:mine}:{opponent:mine};const{error}=await supa().from('game_battles').update(patch).eq('code',r.code).eq('status','waiting').select().maybeSingle();if(error)throw error;await syncRoom()}catch(e){console.error(e);setText('readyHint','Could not update READY. Try again.')}}
async function maybeStart(r){if(r?.status!=='waiting'||!r.creator?.ready||!r.opponent?.ready)return;const at=Date.now()+3500;const creator={...r.creator,battleStartAt:Number(r.creator.battleStartAt)||at};const{data}=await supa().from('game_battles').update({creator,status:'starting'}).eq('code',r.code).eq('status','waiting').select().maybeSingle();if(data)startAt(data)}
function startAt(r){const at=Number(r.creator?.battleStartAt||Date.now()+500);if(startTimer)clearTimeout(startTimer);setText('readyHint','Both ready. Starting together…');startTimer=setTimeout(()=>{setText('battleStatus','FIGHT!');setText('readyHint','Battle started!');window.Character3D?.play?.('attack','left');setTimeout(()=>window.Character3D?.play?.('hit','right'),350);setTimeout(()=>window.Character3D?.play?.('attack','right'),700);setTimeout(()=>window.Character3D?.play?.('hit','left'),1050);finishRound(r)},Math.max(0,at-Date.now()))}
async function finishRound(r){if(!r||r.status!=='starting'||!r.creator||!r.opponent)return;const A=r.creator,B=r.opponent,av=A.power+(A.seed%17),bv=B.power+(B.seed%17),winner=av>=bv?A:B,loser=winner===A?B:A,res={winner,loser,margin:Math.abs(av-bv)};const{data}=await supa().from('game_battles').update({status:'finished',winner,finished_at:new Date().toISOString()}).eq('code',r.code).eq('status','starting').select().maybeSingle();if(data)renderResult(data,res)}
function renderResult(r,res){const localWon=res.winner?.name===monster?.name;setText('battleStatus',localWon?'VICTORY':'DEFEAT');const out=$('#battleResult');if(out)out.innerHTML=`<div class="win-title ${localWon?'you-win':'you-lose'}">${localWon?'VICTORY':'DEFEAT'}</div><p><b>${esc(res.winner.name)}</b> wins with ${res.winner.power} power · margin ${res.margin}</p><div class="streak-box">WIN STREAK <b>${localWon?recordWin():getStreak()}</b></div><button class="primary wide" id="rematchBtn">REMATCH</button><button class="secondary wide" id="fusionBtn">FUSE THESE FIGHTERS</button>`;window.Character3D?.play?.(localWon?'victory':'defeat',localWon?'left':'right');$('#rematchBtn')?.addEventListener('click',createRoom);$('#fusionBtn')?.addEventListener('click',()=>fuse(r.creator,r.opponent))}
const getStreak=()=>Number(localStorage.getItem('who_streak')||0);function recordWin(){const d=today(),last=localStorage.getItem('who_last_win');let s=getStreak();if(last===d)return s;const prev=new Date(Date.now()-86400000).toISOString().slice(0,10);s=last===prev?s+1:1;localStorage.setItem('who_streak',s);localStorage.setItem('who_last_win',d);return s}
async function syncRoom(){const code=room?.code||parseRoute().code||localStorage.getItem(ROOM_KEY);if(!code)return;try{const r=await getRoom(code);if(!r){setRoom(null);setText('readyHint','This room does not exist or has expired.');return}setRoom(r);paintRoom(r);subscribe(r.code);if(r.status==='starting')startAt(r);else if(r.status==='waiting'&&r.creator?.ready&&r.opponent?.ready)maybeStart(r)}catch(e){console.error('syncRoom',e);setText('readyHint','Connection lost. Retrying…')}}
function subscribe(code){if(!code)return;if(channel&&lastRoomCode!==code){db?.removeChannel(channel);channel=null}if(channel)return;lastRoomCode=code;channel=supa().channel('battle:'+code).on('postgres_changes',{event:'*',schema:'public',table:'game_battles',filter:'code=eq.'+code},()=>syncRoom()).subscribe();if(poll)clearInterval(poll);poll=setInterval(()=>{if(document.visibilityState==='visible')syncRoom().catch(()=>{})},1500)}
async function bootRoom(code){if(booting)return;booting=true;ensureReadyUI();code=safeCode(code||parseRoute().code||localStorage.getItem(ROOM_KEY));if(!code){booting=false;return}showRawBattle();try{const r=await getRoom(code);if(!r){setRoom(null);setText('readyHint','This room link is invalid, expired, or already removed.');booting=false;return}setRoom(r);paintRoom(r);subscribe(code);if(r.status==='starting')startAt(r);else if(r.status==='waiting'&&r.creator?.ready&&r.opponent?.ready)maybeStart(r)}catch(e){console.error('bootRoom',e);setText('readyHint','Could not reconnect. Check your internet connection.')}finally{booting=false}}
function showRawBattle(){screens.forEach(x=>$('#'+x)?.classList.toggle('active',x==='battle'));window.scrollTo(0,0);ensureReadyUI()}
async function createRoom(){if(!monster)return;try{const code=Math.random().toString(36).slice(2,8).toUpperCase();const{data,error}=await supa().from('game_battles').insert({code,creator:monster,creator_id:playerId(),status:'waiting',day:today()}).select().single();if(error)throw error;setRoom(data);history.replaceState(null,'',roomUrl(code));showRawBattle();paintRoom(data);subscribe(code);setText('readyHint','Share the room link. Your opponent can open it on another device.');share(false)}catch(e){console.error(e);alert('Battle could not connect to Supabase.')}}
async function joinRoom(code){code=safeCode(code);if(!code){alert('Invalid room link.');return}try{const r=await getRoom(code);if(!r||r.status==='finished'||r.status==='starting'||r.opponent_id)throw Error('full');const m=monster||makeMonster($('#nameInput')?.value.trim()||'Challenger');saveMonster(m);const{data,error}=await supa().from('game_battles').update({opponent:m,opponent_id:playerId()}).eq('code',code).eq('status','waiting').is('opponent_id',null).select().maybeSingle();if(error||!data)throw error||Error('full');setRoom(data);history.replaceState(null,'',roomUrl(code));showRawBattle();paintRoom(data);subscribe(code)}catch(e){console.error(e);alert('This battle is unavailable, full, or already started.')}}
async function generate(){const n=$('#nameInput')?.value.trim();if(!n){$('#nameInput')?.focus();return}const route=parseRoute();const joinCode=$('#nameInput')?.dataset.roomCode||route.code;if(joinCode){const m=saveMonster(makeMonster(n));await joinRoom(joinCode);return}const m=saveMonster(makeMonster(n));renderMonster(m);show('result')}
async function share(showText=true){if(!room?.code)return;const url=roomUrl(room.code);try{await navigator.clipboard?.writeText(url);if(navigator.share&&showText){try{await navigator.share({title:'Join my battle',text:'Join my 3D battle room',url})}catch{}}}catch{}if(showText)setText('shareUrl','LINK COPIED · '+url)}
function loadChallenge(){const route=parseRoute();if(route.type!=='challenge')return;if(route.code){getRoom(route.code).then(r=>{if(r?.creator){setChallenge(r.creator);show('challenge');const btn=$('#acceptChallengeBtn');if(btn)btn.onclick=()=>{show('create');const input=$('#nameInput');if(input){input.value='';input.dataset.roomCode=route.code}}}}).catch(()=>{})}else{show('create');setText('readyHint','This challenge link has no live room. Create a room first.')}}
async function loadLeaderboard(mode,target){const el=$('#'+target);if(!el)return;try{let q=supa().from('game_battles').select('winner,finished_at').eq('status','finished').order('finished_at',{ascending:false}).limit(100);if(mode==='daily')q=q.gte('finished_at',today()+'T00:00:00Z');const{data}=await q;const map={};(data||[]).forEach(x=>{const w=x.winner;if(!w)return;map[w.name]??={name:w.name,wins:0,power:w.power};map[w.name].wins++;map[w.name].power=Math.max(map[w.name].power,w.power||0)});el.innerHTML=Object.values(map).sort((a,b)=>b.wins-a.wins||b.power-a.power).slice(0,10).map(x=>`<div class="rank"><span>${esc(x.name)}</span><small>${x.wins} wins · POWER ${x.power}</small></div>`).join('')||'No battles yet.'}catch{el.textContent='Leaderboard unavailable.'}}
function loadCollection(){const el=$('#collectionList');if(!el)return;let a=[];try{a=JSON.parse(localStorage.getItem('who_collection')||'[]')}catch{}el.innerHTML=a.map(x=>`<div class="rank"><span>${esc(x.name)}</span><small>POWER ${x.power} · ${esc(x.rarity)}</small></div>`).join('')||'No fighters saved yet.'}
function saveCollection(m){let a=[];try{a=JSON.parse(localStorage.getItem('who_collection')||'[]')}catch{}if(!a.some(x=>x.seed===m.seed))a.unshift(m);localStorage.setItem('who_collection',JSON.stringify(a.slice(0,50)))}
function fuse(a,b){const f=makeMonster((a?.name||'A')+(b?.name||'B'));f.name=(a?.name||'A').split(' ')[0]+' × '+(b?.name||'B').split(' ')[0];f.power=Math.min(100,Math.round(((a?.power||50)+(b?.power||50))/2+5));f.rarity=f.power>92?'MYTHIC FUSION':f.power>80?'LEGENDARY FUSION':'EPIC FUSION';saveCollection(f);setText('fusionName',f.name);setText('fusionPower','POWER '+f.power);setText('fusionRarity',f.rarity);window.Character3D?.setSlot?.('#fusion3d',f);show('fusion')}
async function mountHome3D(){if(window.Character3D?.setSlot){await window.Character3D.setSlot('#home3d',makeMonster('Home Knight'));await window.Character3D.setSlot('#home3dAlt',makeMonster('Home Warrior'))}}
function setup(){monster=loadMonster();document.querySelectorAll('[data-home]').forEach(b=>b.addEventListener('click',()=>show('home')));$('#createBtn')?.addEventListener('click',()=>show('create'));$('#generateBtn')?.addEventListener('click',generate);$('#challengeBtn')?.addEventListener('click',createRoom);$('#copyBtn')?.addEventListener('click',()=>share(true));$('#collectionBtn')?.addEventListener('click',()=>{if(monster)saveCollection(monster);show('collection')});$('#openLeaderboard')?.addEventListener('click',()=>show('leaderboard'));window.addEventListener('hashchange',()=>{const r=parseRoute();if(r.type==='room')bootRoom(r.code);else if(r.type==='challenge')loadChallenge()});window.addEventListener('pageshow',()=>setTimeout(()=>{const r=parseRoute();if(r.type==='room')bootRoom(r.code);else if(r.type==='challenge')loadChallenge();else if(localStorage.getItem(ROOM_KEY))bootRoom(localStorage.getItem(ROOM_KEY));else{show('home');mountHome3D()}},100));const route=parseRoute();if(route.type==='room')bootRoom(route.code);else if(route.type==='challenge')loadChallenge();else if(localStorage.getItem(ROOM_KEY))bootRoom(localStorage.getItem(ROOM_KEY));else{show('home');mountHome3D()}}
window.RoomEngine={createRoom,joinRoom,bootRoom,ready,syncRoom,share};window.addEventListener('DOMContentLoaded',setup);
})();